name: Docker-Image-Build-CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the tagged Docker image
        #run: docker build traefik --file traefik/Dockerfile
        run: make build
